In [1]:
%pip install requests
%pip install pandas
%pip install matplotlib
%pip install numpy
%pip install statistics

Requirement already satisfied: requests in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from requests) (2025.7.14)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.3.1)
Requirement already satisfied: packaging>=20.0 in c:\users\rajwi\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: statistics in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (1.0.3.5)
Requirement already satisfied: docutils>=0.3 in c:\users\rajwi\appdata\local\programs\python\python313\lib\site-packages (from statistics) (0.22)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import requests
import pandas as pd

all_products = []
for page in range(1, 130):  # 12 pages × 1000 = 12,000
    url = (
        f"""https://world.openfoodfacts.org/api/v2/search?"
         categories=chocolates&fields=code,product_name,brands,nutriments,nova_group,nutrition_score_fr,
        fruits-vegetables-nuts-estimate-from-ingredients_100g&page_size=1000&page={page}"""
    )
    response = requests.get(url)
    data = response.json().get('products', [])
    all_products.extend(data)

df = pd.json_normalize(all_products)

In [4]:
display(df)

,brands,code,product_name,nutriments.carbohydrates,nutriments.carbohydrates_100g,nutriments.carbohydrates_serving,nutriments.carbohydrates_unit,nutriments.carbohydrates_value,nutriments.energy,nutriments.energy-kcal,...,nutriments.folates_prepared_100g,nutriments.folates_prepared_serving,nutriments.folates_prepared_unit,nutriments.folates_prepared_value,nutriments.vitamin-d2,nutriments.vitamin-d2_100g,nutriments.vitamin-d2_label,nutriments.vitamin-d2_serving,nutriments.vitamin-d2_unit,nutriments.vitamin-d2_value
0,Sidi Ali,6111035000430,Sidi Ali,42.0,4.2,42.0,g,42.0,20.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jaouda,6111242100992,Perly,9.4,9.4,9.4,g,9.4,406.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sidi ali,6111035002175,Sidi Ali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Les Eaux Minérales d'oulmès,Sidi Ali",6111035000058,Eau minérale naturelle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AQUAFINA,6111252421568,اكوافينا,0.0,0.0,0.0,g,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12892,Jordans,5010477342713,Jordans Country Crisp Honey And Nut,61.0,61.0,27.4,g,61.0,1904.0,455.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12893,Tesco,5031021097392,,10.2,10.2,NaN,g,10.2,2408.0,582.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12894,Sainsbury's,00316286,Fat free greek style yogurt,5.2,5.2,5.2,g,5.2,213.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12895,Good life,5012869541803,Spicy veg bean burgers,20.0,17.6,20.0,g,20.0,876.0,210.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12896,Al Hamd,6111203004444,Tartine la Prairie classique 1kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
columns = ['brands',
           'code',
           'product_name',
           'nutriments.energy-kcal_value',
           'nutriments.energy-kj_value',
           'nutriments.carbohydrates_value',
           'nutriments.sugars_value',
           'nutriments.fat_value',
           'nutriments.saturated-fat_value',
           'nutriments.proteins_value',
           'nutriments.fiber_value',
           'nutriments.salt_value',
           'nutriments.sodium_value',
           'nutriments.nova-group',
           'nutriments.nutrition-score-fr',
           'nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g'
]

In [6]:
df = df[columns]
df

,brands,code,product_name,nutriments.energy-kcal_value,nutriments.energy-kj_value,nutriments.carbohydrates_value,nutriments.sugars_value,nutriments.fat_value,nutriments.saturated-fat_value,nutriments.proteins_value,nutriments.fiber_value,nutriments.salt_value,nutriments.sodium_value,nutriments.nova-group,nutriments.nutrition-score-fr,nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g
0,Sidi Ali,6111035000430,Sidi Ali,0.0,20.0,42.0,14.0,0.0,0.0,0.0,0.0,0.00000,0.000000,NaN,1.0,0.00000
1,Jaouda,6111242100992,Perly,97.0,406.0,9.4,NaN,3.0,NaN,8.0,NaN,NaN,NaN,3.0,NaN,0.00000
2,sidi ali,6111035002175,Sidi Ali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,NaN,0.0,0.00000
3,"Les Eaux Minérales d'oulmès,Sidi Ali",6111035000058,Eau minérale naturelle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,1.0,0.0,0.00000
4,AQUAFINA,6111252421568,اكوافينا,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00508,0.002032,NaN,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12892,Jordans,5010477342713,Jordans Country Crisp Honey And Nut,455.0,NaN,61.0,22.0,18.0,2.0,9.4,5.5,0.03000,0.012000,NaN,9.0,0.00000
12893,Tesco,5031021097392,,582.0,2408.0,10.2,7.3,46.4,5.9,24.9,11.6,1.10000,0.440000,3.0,4.0,99.45000
12894,Sainsbury's,00316286,Fat free greek style yogurt,51.0,NaN,5.2,5.2,0.5,0.1,6.4,0.5,0.13750,0.055000,1.0,-1.0,0.00000
12895,Good life,5012869541803,Spicy veg bean burgers,210.0,876.0,20.0,2.0,9.7,0.6,5.8,8.9,0.75000,0.300000,3.0,-3.0,63.36575
12896,Al Hamd,6111203004444,Tartine la Prairie classique 1kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,0.00000

In [7]:
df1 = df.rename(columns={
    'code': 'product_code',
    'product_name': 'product_name',
    'brands': 'brand',
    'nutriments.energy-kcal_value':'energy-kcal_value',
    'nutriments.energy-kj_value':'energy-kj_value',
    'nutriments.carbohydrates_value':'carbohydrates_value',
    'nutriments.sugars_value':'sugars_value',
    'nutriments.fat_value':'fat_value',
    'nutriments.saturated-fat_value':'saturated-fat_value',
    'nutriments.proteins_value':'proteins_value',
    'nutriments.fiber_value':'fiber_value',
    'nutriments.salt_value':'salt_value',
    'nutriments.sodium_value':'sodium_value',
    'nutriments.nova-group':'nova-group',
    'nutriments.nutrition-score-fr':'nutrition-score-fr',
    'nutriments.fruits-vegetables-nuts-estimate-from-ingredients_100g':'fruits-vegetables-nuts-estimate-from-ingredients_100g'
})
df1

,brand,product_code,product_name,energy-kcal_value,energy-kj_value,carbohydrates_value,sugars_value,fat_value,saturated-fat_value,proteins_value,fiber_value,salt_value,sodium_value,nova-group,nutrition-score-fr,fruits-vegetables-nuts-estimate-from-ingredients_100g
0,Sidi Ali,6111035000430,Sidi Ali,0.0,20.0,42.0,14.0,0.0,0.0,0.0,0.0,0.00000,0.000000,NaN,1.0,0.00000
1,Jaouda,6111242100992,Perly,97.0,406.0,9.4,NaN,3.0,NaN,8.0,NaN,NaN,NaN,3.0,NaN,0.00000
2,sidi ali,6111035002175,Sidi Ali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,NaN,0.0,0.00000
3,"Les Eaux Minérales d'oulmès,Sidi Ali",6111035000058,Eau minérale naturelle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,1.0,0.0,0.00000
4,AQUAFINA,6111252421568,اكوافينا,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00508,0.002032,NaN,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12892,Jordans,5010477342713,Jordans Country Crisp Honey And Nut,455.0,NaN,61.0,22.0,18.0,2.0,9.4,5.5,0.03000,0.012000,NaN,9.0,0.00000
12893,Tesco,5031021097392,,582.0,2408.0,10.2,7.3,46.4,5.9,24.9,11.6,1.10000,0.440000,3.0,4.0,99.45000
12894,Sainsbury's,00316286,Fat free greek style yogurt,51.0,NaN,5.2,5.2,0.5,0.1,6.4,0.5,0.13750,0.055000,1.0,-1.0,0.00000
12895,Good life,5012869541803,Spicy veg bean burgers,210.0,876.0,20.0,2.0,9.7,0.6,5.8,8.9,0.75000,0.300000,3.0,-3.0,63.36575
12896,Al Hamd,6111203004444,Tartine la Prairie classique 1kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,0.00000

In [8]:
print(df1.info())
print(df1.describe())
display(df1.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12897 entries, 0 to 12896
Data columns (total 16 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   brand                                                  12310 non-null  object
 1   product_code                                           12897 non-null  object
 2   product_name                                           12608 non-null  object
 3   energy-kcal_value                                      12047 non-null  float64
 4   energy-kj_value                                        6917 non-null   float64
 5   carbohydrates_value                                    12053 non-null  float64
 6   sugars_value                                           11829 non-null  float64
 7   fat_value                                              12077 non-null  float64
 8   saturated-fat_value                                    11750 non-null  float64
 9   proteins_value                                         12067 non-null  float64
 10  fiber_value                                            8799 non-null   float64
 11  salt_value                                             11713 non-null  float64
 12  sodium_value                                           11713 non-null  float64
 13  nova-group                                             11515 non-null  float64
 14  nutrition-score-fr                                     11077 non-null  float64
 15  fruits-vegetables-nuts-estimate-from-ingredients_100g  12093 non-null  float64
dtypes: float64(13), object(3)
memory usage: 1.6+ MB
None
       energy-kcal_value  energy-kj_value  carbohydrates_value  sugars_value  \
count       12047.000000      6917.000000         12053.000000  11829.000000
mean          279.984037      1219.767481            29.618455     11.493078
std           483.355719       846.190922            94.862622     19.339127
min             0.000000         0.000000             0.000000      0.000000
25%            90.002500       419.000000             4.600000      1.000000
50%           241.000000      1190.000000            15.000000      4.100000
75%           432.000000      1866.000000            55.000000     13.000000
max         45793.499044      3768.000000          8989.000000    895.000000

          fat_value  saturated-fat_value  proteins_value   fiber_value  \
count  12077.000000         11750.000000    12067.000000  8.799000e+03
mean      14.821640             5.116119        7.346827  6.945383e+08
std       37.227763            10.941097       29.532339  6.514976e+10
min        0.000000             0.000000        0.000000  0.000000e+00
25%        1.200000             0.300000        1.400000  5.000000e-01
50%        6.200000             1.457500        5.600000  2.400000e+00
75%       21.000000             6.000000        9.400000  5.500000e+00
max     3400.000000           595.000000     3000.000000  6.111242e+12

         salt_value  sodium_value    nova-group  nutrition-score-fr  \
count  11713.000000  11713.000000  11515.000000        11077.000000
mean      17.895806      7.158322      3.299436            8.941049
std      808.025051    323.210020      1.011895            9.782884
min        0.000000      0.000000      1.000000          -16.000000
25%        0.050000      0.020000      3.000000            1.000000
50%        0.372800      0.149120      4.000000            7.000000
75%        1.000000      0.400000      4.000000           16.000000
max    85000.000000  34000.000000      4.000000           51.000000

       fruits-vegetables-nuts-estimate-from-ingredients_100g
count                                       12093.000000
mean                                           18.243847
std                                            30.734163
min                                            -0.066406
25%                                             0.000000
50%                                             0.159226
75%                                            22.000000
max                                           197.200000

(12897, 16)

In [9]:
df1.isnull().sum()
df1.duplicated().sum()

np.int64(0)

In [10]:
display(df1[df1.isnull().any(axis=1)])

,brand,product_code,product_name,energy-kcal_value,energy-kj_value,carbohydrates_value,sugars_value,fat_value,saturated-fat_value,proteins_value,fiber_value,salt_value,sodium_value,nova-group,nutrition-score-fr,fruits-vegetables-nuts-estimate-from-ingredients_100g
0,Sidi Ali,6111035000430,Sidi Ali,0.0,20.0,42.0,14.0,0.0,0.0,0.0,0.0,0.00000,0.000000,NaN,1.0,0.0
1,Jaouda,6111242100992,Perly,97.0,406.0,9.4,NaN,3.0,NaN,8.0,NaN,NaN,NaN,3.0,NaN,0.0
2,sidi ali,6111035002175,Sidi Ali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,NaN,0.0,0.0
3,"Les Eaux Minérales d'oulmès,Sidi Ali",6111035000058,Eau minérale naturelle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,1.0,0.0,0.0
4,AQUAFINA,6111252421568,اكوافينا,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00508,0.002032,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12888,Grenade,5060221205269,GRENADE High Protein Salted Peanut Low Sugar,242.0,NaN,19.0,2.0,12.0,5.8,20.0,2.5,NaN,NaN,4.0,NaN,9.6
12890,Late July Snacks,0815099020309,Organic Sea Salt Multigrain Tortilla Chips,140.0,NaN,17.0,1.0,7.0,0.5,2.0,2.0,0.23750,0.095000,3.0,8.0,0.0
12892,Jordans,5010477342713,Jordans Country Crisp Honey And Nut,455.0,NaN,61.0,22.0,18.0,2.0,9.4,5.5,0.03000,0.012000,NaN,9.0,0.0
12894,Sainsbury's,00316286,Fat free greek style yogurt,51.0,NaN,5.2,5.2,0.5,0.1,6.4,0.5,0.13750,0.055000,1.0,-1.0,0.0
12896,Al Hamd,6111203004444,Tartine la Prairie classique 1kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,0.0

In [11]:
numerical_df = df1.select_dtypes(include='number')

all_null_numerical_rows = df1[numerical_df.isnull().all(axis=1)]

display(all_null_numerical_rows)

,brand,product_code,product_name,energy-kcal_value,energy-kj_value,carbohydrates_value,sugars_value,fat_value,saturated-fat_value,proteins_value,fiber_value,salt_value,sodium_value,nova-group,nutrition-score-fr,fruits-vegetables-nuts-estimate-from-ingredients_100g
196,NaN,7322540548563,jempo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,NaN,6111246651261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,NaN,6111175000741,41022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
472,NaN,6111259733749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
578,,5011321361058,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12567,NaN,8437027936005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12569,NaN,6111251732870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12570,Bifa,8690562008211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12571,NaN,6111266420175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12796,Woolworths,9300633929169,Chunk Light Tuna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df1 = df1.drop(all_null_numerical_rows.index)
display(df1)

,brand,product_code,product_name,energy-kcal_value,energy-kj_value,carbohydrates_value,sugars_value,fat_value,saturated-fat_value,proteins_value,fiber_value,salt_value,sodium_value,nova-group,nutrition-score-fr,fruits-vegetables-nuts-estimate-from-ingredients_100g
0,Sidi Ali,6111035000430,Sidi Ali,0.0,20.0,42.0,14.0,0.0,0.0,0.0,0.0,0.00000,0.000000,NaN,1.0,0.00000
1,Jaouda,6111242100992,Perly,97.0,406.0,9.4,NaN,3.0,NaN,8.0,NaN,NaN,NaN,3.0,NaN,0.00000
2,sidi ali,6111035002175,Sidi Ali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,NaN,0.0,0.00000
3,"Les Eaux Minérales d'oulmès,Sidi Ali",6111035000058,Eau minérale naturelle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,26.000000,1.0,0.0,0.00000
4,AQUAFINA,6111252421568,اكوافينا,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00508,0.002032,NaN,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12892,Jordans,5010477342713,Jordans Country Crisp Honey And Nut,455.0,NaN,61.0,22.0,18.0,2.0,9.4,5.5,0.03000,0.012000,NaN,9.0,0.00000
12893,Tesco,5031021097392,,582.0,2408.0,10.2,7.3,46.4,5.9,24.9,11.6,1.10000,0.440000,3.0,4.0,99.45000
12894,Sainsbury's,00316286,Fat free greek style yogurt,51.0,NaN,5.2,5.2,0.5,0.1,6.4,0.5,0.13750,0.055000,1.0,-1.0,0.00000
12895,Good life,5012869541803,Spicy veg bean burgers,210.0,876.0,20.0,2.0,9.7,0.6,5.8,8.9,0.75000,0.300000,3.0,-3.0,63.36575
12896,Al Hamd,6111203004444,Tartine la Prairie classique 1kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,0.00000

In [13]:
brand_null_rows = df1[df1['brand'].isnull()]
display(brand_null_rows)

,brand,product_code,product_name,energy-kcal_value,energy-kj_value,carbohydrates_value,sugars_value,fat_value,saturated-fat_value,proteins_value,fiber_value,salt_value,sodium_value,nova-group,nutrition-score-fr,fruits-vegetables-nuts-estimate-from-ingredients_100g
154,NaN,6111214004747,Pipas,520.0,2177.0,38.9,1.65,29.0,3.36,24.60,2.7,0.059,0.0236,3.0,-5.0,0.0
166,NaN,6111245591063,Dalaa 550 feuilles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
178,NaN,6111032000631,Salim,58.0,NaN,NaN,4.80,3.0,2.00,3.00,NaN,NaN,NaN,NaN,NaN,0.0
279,NaN,6111266962446,6111266962446,167.8,703.9,NaN,20.00,7.4,4.80,5.30,NaN,0.000,0.0000,4.0,11.0,0.0
280,NaN,6111180003102,Mayfine,356.0,NaN,85.0,0.00,0.6,0.00,0.45,0.0,0.071,0.0284,3.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12507,NaN,6111073504266,Moutarde de dijon,140.0,NaN,4.6,2.00,10.3,0.60,7.30,NaN,5.600,2.2400,NaN,21.0,NaN
12508,NaN,6111259342903,Bé Bunny,409.0,NaN,51.9,26.90,19.6,3.10,6.10,NaN,0.100,0.0400,NaN,15.0,NaN
12509,NaN,6111250472098,Le FER,49.0,NaN,12.0,12.00,0.5,0.10,0.50,0.5,0.025,0.0100,4.0,NaN,0.0
12522,NaN,6111035001772,Oulmes,0.0,NaN,0.0,0.00,0.0,0.00,0.00,NaN,0.313,0.1252,1.0,1.0,NaN
12568,NaN,6111099000193,Lousra,900.0,NaN,0.0,NaN,100.0,15.00,0.00,NaN,0.000,0.0000,NaN,NaN,0.0

In [14]:
df1 = df1.drop(brand_null_rows.index)

In [15]:
product_name =df1[df1['product_name'].isnull()]
display(product_name)

,brand,product_code,product_name,energy-kcal_value,energy-kj_value,carbohydrates_value,sugars_value,fat_value,saturated-fat_value,proteins_value,fiber_value,salt_value,sodium_value,nova-group,nutrition-score-fr,fruits-vegetables-nuts-estimate-from-ingredients_100g
112,lio,6111099000599,NaN,900.0,3768.0,0.00,0.00,100.00,14.00,0.0,0.00,NaN,NaN,2.0,NaN,NaN
234,Jibal,6111246953679,NaN,105.0,438.0,NaN,10.00,3.80,2.50,6.5,NaN,0.2500,0.1000,1.0,14.0,0.000000
430,رفيع,6111242882263,NaN,45.0,NaN,4.80,NaN,1.50,NaN,3.2,NaN,NaN,NaN,4.0,NaN,58.333333
466,Délicia,6111162000822,NaN,250.0,1062.0,61.33,61.33,0.30,0.00,0.5,0.00,0.0000,0.0000,NaN,17.0,NaN
607,Excelo,6111249961466,NaN,424.0,1771.0,65.70,40.80,15.30,9.70,5.7,NaN,0.6200,0.2480,NaN,28.0,NaN
761,Ladid,6111266962675,NaN,270.0,888.4,7.60,7.60,16.50,11.50,7.4,NaN,3.2500,1.3000,NaN,27.0,NaN
954,Nestle,6111018909194,NaN,144.0,NaN,17.80,14.10,4.60,2.30,4.0,0.80,195.0000,78.0000,4.0,NaN,0.000000
968,Be,6111259346710,NaN,232.0,NaN,28.00,14.00,12.00,6.00,2.0,1.00,0.2500,0.1000,NaN,27.0,NaN
1159,Or Blanc,6111245340487,NaN,226.0,NaN,6.50,5.90,18.00,12.00,9.5,0.35,4.2500,1.7000,4.0,30.0,0.000000
1652,"Coca-Cola, Coca-Cola Company",5449000311856,NaN,27.5,117.0,6.66,6.00,NaN,NaN,NaN,NaN,42.0000,16.8000,4.0,NaN,3.000000
2355,Snickers,5000159559003,NaN,245.0,NaN,NaN,25.00,12.00,3.80,NaN,NaN,0.6500,0.2600,NaN,NaN,0.000000
2430,Pipas de la casa,3400938267266,NaN,888.0,255.0,8989.00,895.00,554.00,595.00,597.0,8909.00,898.0000,359.2000,3.0,50.0,0.000000
2780,La Délicieuse,6111250471572,NaN,NaN,1008.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2991,Ferrero,8000500367582,NaN,80.0,NaN,0.00,0.00,8.00,1.50,0.0,0.00,0.0040,0.0016,3.0,15.0,13.000000
3041,Excelo,6111259343801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,6.097561
3590,Marsa,0769503575469,NaN,239.2,NaN,1.20,NaN,14.50,NaN,26.2,NaN,NaN,NaN,NaN,NaN,0.000000
4003,Cream cheese,6111246722084,NaN,100.0,NaN,1.00,1.00,10.00,6.00,2.0,0.00,237.5000,95.0000,3.0,15.0,0.000000
4650,Lay's,6111255772940,NaN,NaN,1919.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4877,Rifnuts,6111258520012,NaN,300.0,NaN,10.00,NaN,25.00,3.50,10.0,NaN,1.7500,0.7000,NaN,NaN,0.000000
4880,Wedo,6111271590504,NaN,50.0,NaN,55.00,20.00,35.00,40.00,30.0,86.00,150.0000,60.0000,4.0,NaN,0.000000
4979,Excelo,6111259344075,NaN,541.0,NaN,57.50,56.30,31.50,8.10,6.3,3.40,0.2500,0.1000,NaN,NaN,NaN
6360,Aiguebelle,6111017047873,NaN,507.0,2108.0,33.00,28.00,47.60,23.00,NaN,NaN,0.0100,0.0040,NaN,NaN,NaN
6851,Excelo,12301218,NaN,564.0,NaN,NaN,63.00,20.40,NaN,6.2,NaN,NaN,NaN,NaN,NaN,NaN
8785,Gust Original,5942321000077,NaN,42.0,NaN,10.60,10.60,0.00,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
10396,Hacendado,8402001017698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
10771,Hacendado,8402001014307,NaN,709.0,NaN,2.90,NaN,68.20,NaN,18.0,5.90,17.7025,7.0810,1.0,NaN,100.000000
10901,Hacendado,8480000124951,NaN,580.0,2402.0,33.00,29.00,44.00,27.00,7.4,11.00,0.0000,0.0000,4.0,20.0,0.000000
11606,Pharmalife,8051128634501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,0.000000
11607,jibal,6111246954508,NaN,73.0,310.0,13.02,10.64,1.15,0.77,2.7,0.00,0.0000,0.0000,4.0,2.0,0.000000
11981,Lune de Miel,3088541015209,NaN,320.0,NaN,80.00,62.00,0.00,NaN,0.0,NaN,NaN,NaN,2.0,NaN,0.000000
12033,"Arla Foods, Arla",5711953176616,NaN,43.0,179.0,7.30,3.10,0.90,0.10,0.9,1.00,0.1000,0.0400,4.0,5.0,0.000000
12056,Aldi,4061463564061,NaN,69.0,NaN,12.80,0.30,1.30,0.10,1.4,0.30,0.1575,0.0630,3.0,6.0,0.000000
12533,,8710472001543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
12536,Bucovina,59492993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000

In [16]:
df1 = df1.drop(product_name.index)

In [17]:
display(df1.shape)

(12145, 16)

In [18]:
for i in ['energy-kcal_value',
          'energy-kj_value',
          'carbohydrates_value',
          'sugars_value',
          'fat_value',
          'saturated-fat_value',
          'proteins_value',
          'fiber_value',
          'salt_value',
          'sodium_value',
          'nova-group',
          'nutrition-score-fr',
          'fruits-vegetables-nuts-estimate-from-ingredients_100g']:
    df1[i] = pd.to_numeric(df1[i], errors='coerce')
    df1[i] = df1[i].fillna(df1[i].median())

In [19]:
df1.isnull().sum()

brand                                                    0
product_code                                             0
product_name                                             0
energy-kcal_value                                        0
energy-kj_value                                          0
carbohydrates_value                                      0
sugars_value                                             0
fat_value                                                0
saturated-fat_value                                      0
proteins_value                                           0
fiber_value                                              0
salt_value                                               0
sodium_value                                             0
nova-group                                               0
nutrition-score-fr                                       0
fruits-vegetables-nuts-estimate-from-ingredients_100g    0
dtype: int64

In [20]:
display(df1)

,brand,product_code,product_name,energy-kcal_value,energy-kj_value,carbohydrates_value,sugars_value,fat_value,saturated-fat_value,proteins_value,fiber_value,salt_value,sodium_value,nova-group,nutrition-score-fr,fruits-vegetables-nuts-estimate-from-ingredients_100g
0,Sidi Ali,6111035000430,Sidi Ali,0.0,20.0,42.0,14.0,0.0,0.0,0.0,0.0,0.00000,0.000000,4.0,1.0,0.00000
1,Jaouda,6111242100992,Perly,97.0,406.0,9.4,4.1,3.0,1.4,8.0,2.5,0.38000,0.152000,3.0,7.0,0.00000
2,sidi ali,6111035002175,Sidi Ali,241.0,1190.0,15.0,4.1,6.1,1.4,5.7,2.5,65.00000,26.000000,4.0,0.0,0.00000
3,"Les Eaux Minérales d'oulmès,Sidi Ali",6111035000058,Eau minérale naturelle,241.0,1190.0,15.0,4.1,6.1,1.4,5.7,2.5,65.00000,26.000000,1.0,0.0,0.00000
4,AQUAFINA,6111252421568,اكوافينا,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00508,0.002032,4.0,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12892,Jordans,5010477342713,Jordans Country Crisp Honey And Nut,455.0,1190.0,61.0,22.0,18.0,2.0,9.4,5.5,0.03000,0.012000,4.0,9.0,0.00000
12893,Tesco,5031021097392,,582.0,2408.0,10.2,7.3,46.4,5.9,24.9,11.6,1.10000,0.440000,3.0,4.0,99.45000
12894,Sainsbury's,00316286,Fat free greek style yogurt,51.0,1190.0,5.2,5.2,0.5,0.1,6.4,0.5,0.13750,0.055000,1.0,-1.0,0.00000
12895,Good life,5012869541803,Spicy veg bean burgers,210.0,876.0,20.0,2.0,9.7,0.6,5.8,8.9,0.75000,0.300000,3.0,-3.0,63.36575
12896,Al Hamd,6111203004444,Tartine la Prairie classique 1kg,241.0,1190.0,15.0,4.1,6.1,1.4,5.7,2.5,0.38000,0.152000,4.0,7.0,0.00000

In [21]:
# Sugar to carb ratio
df1['sugar_to_carb_ratio'] = df1['sugars_value'] / df1['carbohydrates_value']

# Calorie Category
def calorie_cat(val):
    if val < 200: return 'Low'
    elif val <= 450: return 'Moderate'
    else: return 'High'
df1['calorie_category'] = df1['energy-kcal_value'].apply(calorie_cat)

# Sugar Category
def sugar_cat(val):
    if val < 20: return 'Low Sugar'
    elif val <= 40: return 'Moderate Sugar'
    else: return 'High Sugar'
df1['sugar_category'] = df1['sugars_value'].apply(sugar_cat)

# Ultra processed flag
df1['is_ultra_processed'] = df1['nova-group'].apply(lambda x: 'Yes' if x == 4 else 'No')

In [22]:
df1.columns

Index(['brand', 'product_code', 'product_name', 'energy-kcal_value',
       'energy-kj_value', 'carbohydrates_value', 'sugars_value', 'fat_value',
       'saturated-fat_value', 'proteins_value', 'fiber_value', 'salt_value',
       'sodium_value', 'nova-group', 'nutrition-score-fr',
       'fruits-vegetables-nuts-estimate-from-ingredients_100g',
       'sugar_to_carb_ratio', 'calorie_category', 'sugar_category',
       'is_ultra_processed'],
      dtype='object')

In [23]:
display(df1)

,brand,product_code,product_name,energy-kcal_value,energy-kj_value,carbohydrates_value,sugars_value,fat_value,saturated-fat_value,proteins_value,fiber_value,salt_value,sodium_value,nova-group,nutrition-score-fr,fruits-vegetables-nuts-estimate-from-ingredients_100g,sugar_to_carb_ratio,calorie_category,sugar_category,is_ultra_processed
0,Sidi Ali,6111035000430,Sidi Ali,0.0,20.0,42.0,14.0,0.0,0.0,0.0,0.0,0.00000,0.000000,4.0,1.0,0.00000,0.333333,Low,Low Sugar,Yes
1,Jaouda,6111242100992,Perly,97.0,406.0,9.4,4.1,3.0,1.4,8.0,2.5,0.38000,0.152000,3.0,7.0,0.00000,0.436170,Low,Low Sugar,No
2,sidi ali,6111035002175,Sidi Ali,241.0,1190.0,15.0,4.1,6.1,1.4,5.7,2.5,65.00000,26.000000,4.0,0.0,0.00000,0.273333,Moderate,Low Sugar,Yes
3,"Les Eaux Minérales d'oulmès,Sidi Ali",6111035000058,Eau minérale naturelle,241.0,1190.0,15.0,4.1,6.1,1.4,5.7,2.5,65.00000,26.000000,1.0,0.0,0.00000,0.273333,Moderate,Low Sugar,No
4,AQUAFINA,6111252421568,اكوافينا,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00508,0.002032,4.0,0.0,0.00000,NaN,Low,Low Sugar,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12892,Jordans,5010477342713,Jordans Country Crisp Honey And Nut,455.0,1190.0,61.0,22.0,18.0,2.0,9.4,5.5,0.03000,0.012000,4.0,9.0,0.00000,0.360656,High,Moderate Sugar,Yes
12893,Tesco,5031021097392,,582.0,2408.0,10.2,7.3,46.4,5.9,24.9,11.6,1.10000,0.440000,3.0,4.0,99.45000,0.715686,High,Low Sugar,No
12894,Sainsbury's,00316286,Fat free greek style yogurt,51.0,1190.0,5.2,5.2,0.5,0.1,6.4,0.5,0.13750,0.055000,1.0,-1.0,0.00000,1.000000,Low,Low Sugar,No
12895,Good life,5012869541803,Spicy veg bean burgers,210.0,876.0,20.0,2.0,9.7,0.6,5.8,8.9,0.75000,0.300000,3.0,-3.0,63.36575,0.100000,Moderate,Low Sugar,No
12896,Al Hamd,6111203004444,Tartine la Prairie classique 1kg,241.0,1190.0,15.0,4.1,6.1,1.4,5.7,2.5,0.38000,0.152000,4.0,7.0,0.00000,0.273333,Moderate,Low Sugar,Yes

In [34]:
df1['sugar_to_carb_ratio'] = pd.to_numeric(df1['sugar_to_carb_ratio'], errors='coerce')
df1['sugar_to_carb_ratio'] = df1['sugar_to_carb_ratio'].fillna(df1['sugar_to_carb_ratio'].median())

In [35]:
import numpy as np

# Replace NaN and inf with None (MySQL NULL)
df1 = df1.replace([np.inf, -np.inf], np.nan)
df1 = df1.where(pd.notnull(df1), None)

In [44]:
df1.isnull().sum()

brand                                                    0
product_code                                             0
product_name                                             0
energy-kcal_value                                        0
energy-kj_value                                          0
carbohydrates_value                                      0
sugars_value                                             0
fat_value                                                0
saturated-fat_value                                      0
proteins_value                                           0
fiber_value                                              0
salt_value                                               0
sodium_value                                             0
nova-group                                               0
nutrition-score-fr                                       0
fruits-vegetables-nuts-estimate-from-ingredients_100g    0
sugar_to_carb_ratio                                      0
calorie_category                                         0
sugar_category                                           0
is_ultra_processed                                       0
dtype: int64

In [45]:
df1.to_csv('chocolate_products_cleaned.csv', index=False)